// build.js
// ============================================================
// Generación de config.js a partir de variables de entorno.
// Vercel corre este script en cada deploy (definido en vercel.json).
//
// En desarrollo local: no toca nada, así que podés mantener tu
// config.js con credenciales manualmente.
//
// En deploy (Vercel): lee SUPABASE_URL y SUPABASE_ANON_KEY de las
// env vars configuradas en el dashboard de Vercel, y escribe un
// config.js nuevo con esos valores.
// ============================================================

const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';
const configPath = path.join(__dirname, 'js', 'config.js');

const content = `// Auto-generated by build.js at ${new Date().toISOString()}
// DO NOT edit in production — changes will be overwritten on next deploy.
window.FBA_CONFIG = {
    supabase: {
        url: ${JSON.stringify(url)},
        anonKey: ${JSON.stringify(key)},
    }
};
`;

// Solo regenerar el archivo cuando estamos en Vercel.
// Vercel setea automáticamente VERCEL=1 durante el build.
if (process.env.VERCEL) {
    fs.writeFileSync(configPath, content);
    if (url && key) {
        console.log('✓ config.js generated from env vars');
        console.log(`  URL: ${url.replace(/^https:\/\/([^.]+)\..*/, 'https://$1.supabase.co')}`);
        console.log(`  Key: ${key.substring(0, 20)}...`);
    } else {
        console.warn('⚠ Missing Supabase env vars — config.js generated with empty credentials.');
        console.warn('  → Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel → Settings → Environment Variables.');
    }
} else {
    console.log('[build.js] Not running in Vercel, skipping config.js generation.');
    console.log('           (Local dev: manage js/config.js manually.)');
}
